#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyroute2.nslink
Version  : 0.6.5
Release  : 9
URL      : https://files.pythonhosted.org/packages/e3/f8/61300f8310714d2f02235b95b1318d77fc117b22c60bf5e63aa49a2883e6/pyroute2.nslink-0.6.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/e3/f8/61300f8310714d2f02235b95b1318d77fc117b22c60bf5e63aa49a2883e6/pyroute2.nslink-0.6.5.tar.gz
Summary  : Python Netlink library: NetNS, NSPopen and remote modules
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 GPL-2.0+
Requires: pyroute2.nslink-license = %{version}-%{release}
Requires: pyroute2.nslink-python = %{version}-%{release}
Requires: pyroute2.nslink-python3 = %{version}-%{release}
Requires: pyroute2.core
BuildRequires : buildreq-distutils3
BuildRequires : pyroute2.core

%description
===============
        
        PyRoute2 is a pure Python **netlink** library.
        
        This module provides NetNS, NSPopen and RemoteSocket classes.
        
        links
        =====

%package license
Summary: license components for the pyroute2.nslink package.
Group: Default

%description license
license components for the pyroute2.nslink package.


%package python
Summary: python components for the pyroute2.nslink package.
Group: Default
Requires: pyroute2.nslink-python3 = %{version}-%{release}

%description python
python components for the pyroute2.nslink package.


%package python3
Summary: python3 components for the pyroute2.nslink package.
Group: Default
Requires: python3-core
Provides: pypi(pyroute2.nslink)
Requires: pypi(pyroute2.core)

%description python3
python3 components for the pyroute2.nslink package.


%prep
%setup -q -n pyroute2.nslink-0.6.5
cd %{_builddir}/pyroute2.nslink-0.6.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632182340
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyroute2.nslink
cp %{_builddir}/pyroute2.nslink-0.6.5/LICENSE.Apache.v2 %{buildroot}/usr/share/package-licenses/pyroute2.nslink/cd9bad64b174708395f795bb92f7b4be7d996e8f
cp %{_builddir}/pyroute2.nslink-0.6.5/LICENSE.GPL.v2 %{buildroot}/usr/share/package-licenses/pyroute2.nslink/4cc77b90af91e615a64ae04893fdffa7939db84c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyroute2.nslink/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/pyroute2.nslink/cd9bad64b174708395f795bb92f7b4be7d996e8f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
